Docker build refreshment  (#13)
* do not rebuilt mina when is already built in min CI. just use debians. Also do not rebuild auxiliary services just get release of them

diff --git a/configuration/Dockerfile b/configuration/Dockerfile
--- a/configuration/Dockerfile
+++ b/configuration/Dockerfile
@@ -1,41 +1,82 @@
 FROM postgres:14-bookworm
 
-RUN apt update \
-  && apt install -y --no-install-recommends \
-  python3 python3-pip jq wget curl psmisc libpq-dev libjemalloc-dev libffi-dev nginx netcat-traditional \
-  && apt clean \
-  && rm -rf /var/lib/apt/lists/*
+ARG MINA_BRANCH=develop
+ARG MINA_REPO=https://nightly.apt.packages.minaprotocol.com
+ARG MINA_ACCOUNTS_MANAGER_VERSION=0.1.1
+ARG ARCHIVE_NODE_API_VERSION=0.0.8
+ARG MINA_PROFILE=devnet
+# Extra profile like lightnet
+ARG MINA_EXTRA_PROFILE
 
-ENV NODE_VERSION=22.9.0
-RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
-ENV NVM_DIR=/root/.nvm
-RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
-RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
-RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
-RUN . "$NVM_DIR/nvm.sh" && npm install -g npm
-ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
-RUN node --version && npm --version
+ENV NODE_VERSION=20.11.1
+ARG TARGETARCH
 
-COPY mina-local-network-2-1-1/ /root/.mina-network/mina-local-network-2-1-1/
-COPY nginx.conf /root/
-COPY spinup-testnet.sh /root/
-COPY mina-local-network.sh /root/
-COPY drop_tables.sql /root/
-COPY create_schema.sql /root/
-COPY mina.exe /root/
-COPY archive.exe /root/
-COPY libp2p_helper /root/
-COPY Archive-Node-API/ /root/Archive-Node-API/
-# COPY accounts-manager /root/
+# Build MINA debian package name
+ENV MINA_DEB_NAME="mina-${MINA_PROFILE}${MINA_EXTRA_PROFILE:+-$MINA_EXTRA_PROFILE}"
+
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    python3 \
+    python3-pip \
+    jq \
+    curl \
+    psmisc \
+    libpq-dev \
+    libjemalloc-dev \
+    libffi-dev \
+    nginx \
+    netcat-traditional \
+    && apt-get clean && rm -rf /var/lib/apt/lists/*
+
+# install Node.js
+RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
+    && apt-get install -y --no-install-recommends nodejs=${NODE_VERSION}-1nodesource1 \
+    && node --version \
+    && npm --version
+
+COPY ./configuration/mina-local-network/ /root/.mina-network/
+COPY ./configuration/nginx.conf /root/
+
+COPY ./scripts/spinup-testnet.sh /root/
+RUN chmod +x /root/spinup-testnet.sh
+
+COPY ./scripts/wait-for-network.sh /root/
+RUN chmod +x /root/wait-for-network.sh
+
+ENV MINA_COMMIT=aa93c44428e7c73cd7b77900634522108b746d18
+
+# download mina-local-network.sh script
+RUN mkdir -p /root/scripts/mina-local-network
+
+RUN curl -fsSL https://raw.githubusercontent.com/MinaProtocol/mina/${MINA_COMMIT}/scripts/mina-local-network/mina-local-network.sh -o /root/scripts/mina-local-network/mina-local-network.sh \
+    && curl -fsSL https://raw.githubusercontent.com/MinaProtocol/mina/${MINA_COMMIT}/scripts/mina-local-network/generate-mina-local-network-ledger.py -o /root/scripts/mina-local-network/generate-mina-local-network-ledger.py \
+    && curl -fsSL https://raw.githubusercontent.com/MinaProtocol/mina/${MINA_COMMIT}/scripts/mina-local-network/requirements.txt -o /root/scripts/mina-local-network/requirements.txt \
+    && chmod +x /root/scripts/mina-local-network/mina-local-network.sh \
+    && chmod +x /root/scripts/mina-local-network/generate-mina-local-network-ledger.py \
+    && pip3 install --no-cache-dir --break-system-packages -r /root/scripts/mina-local-network/requirements.txt
+
+# install mina
+RUN curl -fsSL ${MINA_REPO}/repo-signing-key.gpg -o /etc/apt/trusted.gpg.d/minaprotocol.gpg \
+    && echo "deb ${MINA_REPO} bookworm ${MINA_BRANCH}" | tee /etc/apt/sources.list.d/mina.list \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends mina-logproc ${MINA_DEB_NAME} mina-archive-${MINA_PROFILE} \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/*
+
+# remove magic config files (it makes sense for artificial testnet only, like the one we are going to spin up)
+# otherwise, if you try to run a node with such config, it will fail as devnet might contain some hardcoded data like fork config
+# that will not be valid for other networks
+RUN rm -f /var/lib/coda/config_*.json
+
+# install Mina Archive Node GraphQL API from npm registry
+RUN npm install -g mina-archive-node-graphql@${ARCHIVE_NODE_API_VERSION}
+
+# install Mina Accounts Manager
+RUN curl -fsSL https://github.com/shimkiv/mina-accounts-manager/releases/download/v${MINA_ACCOUNTS_MANAGER_VERSION}/accounts-manager-${TARGETARCH} -o accounts-manager-${TARGETARCH} \
+    && chmod +x accounts-manager-${TARGETARCH} \
+    && mv accounts-manager-${TARGETARCH} /usr/local/bin/accounts-manager
 
 WORKDIR /root
-
-RUN chmod +x mina.exe \
-  && chmod +x archive.exe \
-  && chmod +x libp2p_helper \
-  && chmod +x spinup-testnet.sh \
-  && chmod +x mina-local-network.sh
-# && chmod +x accounts-manager
 
 EXPOSE 3085
 EXPOSE 4001
@@ -44,20 +85,18 @@ EXPOSE 5001
 EXPOSE 5432
 EXPOSE 6001
 EXPOSE 8080
-# EXPOSE 8181
 EXPOSE 8282
 
 ENV RUN_ARCHIVE_NODE="true"
 ENV NETWORK_TYPE="single-node"
 ENV PROOF_LEVEL="full"
 ENV LOG_LEVEL="Trace"
-ENV SLOT_TIME=20000
-ENV MINA_LIBP2P_HELPER_PATH=/root/libp2p_helper
 ENV POSTGRES_USER=postgres
 ENV POSTGRES_PASSWORD=postgres
 ENV POSTGRES_DB=archive
+ENV SLOT_TIME=20000
 
-RUN ./mina.exe --version
+RUN mina --version
 
 ENTRYPOINT [ "bash", "-c" ]
 CMD [ "/root/spinup-testnet.sh" ]
